version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    target-branch: "test"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
