/* Quiz questions for Module 5: Memory Management */

import { QuizQuestion } from "../../shared/types";

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    question: "What does the CPU use to determine which memory addresses to fetch data and instructions from?",
    options: [
      "Page table", "Base register", "Program counter", "MMU relocation register"],
    correctAnswer: 2,
    explanation: "The program counter holds the address of the next instruction to fetch, guiding the CPU through memory as the program executes.",
  },
  {
    id: 2,
    question: "Which address binding method requires the program to be recompiled if its memory location changes?",
    options: ["Load time binding", "Execution time binding", "Compile time binding", "Dynamic binding"],
    correctAnswer: 2,
    explanation: "Compile time binding embeds absolute addresses directly into the executable, any change in memory location requires a full recompilation.",
  },
  {
    id: 3,
    question: "Which address binding method delays the final address determination until the program is loaded into memory?",
    options: ["Compile time binding", "Load time binding", "Execution time binding", "Static binding"],
    correctAnswer: 1,
    explanation: "Load time binding uses relocatable code generated by the compiler, allowing the loader to assign final addresses when the program is placed in memory.",
  },
  {
    id: 4,
    question: "What hardware component translates logical addresses to physical addresses?",
    options: ["Program counter", "Page table", "Memory Management Unit", "Limit register"],
    correctAnswer: 2,
    explanation: "The MMU performs address translation at runtime by adding the relocation register value to every logical address a process generates.",
  },
  {
    id: 5,
    question: "What is the formula for calculating a physical address?",
    options: [
      "Physical Address = Logical Address × Base Register",
      "Physical Address = Logical Address − Base Register",
      "Physical Address = Logical Address + Base Register",
      "Physical Address = Base Register ÷ Logical Address",
    ],
    correctAnswer: 2,
    explanation: "The MMU adds the base register value to the logical address generated by the CPU to produce the actual physical memory address.",
  },
  {
    id: 6,
    question: "Which linking method bundles library code into the executable at compile time, causing every program to carry its own copy?",
    options: ["Dynamic linking", "Dynamic loading", "Runtime linking", "Static linking"],
    correctAnswer: 3,
    explanation: "Static linking merges library code into the executable at compile time, which wastes disk and memory since every program that uses the library gets its own separate copy.",
  },
  {
    id: 7,
    question: "Which memory technique loads a routine into memory only when it is actually called?",
    options: ["Static linking", "Dynamic loading", "Swapping", "Dynamic linking"],
    correctAnswer: 1,
    explanation: "Dynamic loading defers loading any routine until it is called at runtime, so unused routines are never loaded and memory is saved without requiring OS support.",
  },
  {
    id: 8,
    question: "A 20,000-word job is swapped with a transfer rate of 250,000 words/sec and 8 ms latency. What is the total round-trip swap time?",
    options: ["88 ms", "160 ms", "176 ms", "96 ms"],
    correctAnswer: 2,
    explanation: "Transfer = 80 ms, one-way swap = 80 + 8 = 88 ms, and the round-trip (swap out + swap in) = 88 × 2 = 176 ms.",
  },
  {
    id: 9,
    question: "Which type of fragmentation occurs when a process is given more memory than it needs, wasting the leftover space inside the partition?",
    options: ["External fragmentation", "Page fragmentation", "Internal fragmentation", "Allocation fragmentation"],
    correctAnswer: 2,
    explanation: "Internal fragmentation is wasted space inside an allocated memory partition because the process received more memory than it actually required.",
  },
  {
    id: 10,
    question: "Which memory management scheme eliminates external fragmentation by loading pages into any available free frame?",
    options: ["Best fit", "Swapping", "Segmentation", "Paging"],
    correctAnswer: 3,
    explanation: "Paging divides both logical and physical memory into fixed equal-size units, allowing pages to fill any free frame and eliminating the need for contiguous free memory.",
  },
];