/* Memory Management */

export interface Module5Section {
  id: string;
  title: string;
  content: string;
}

export const module5Sections: Module5Section[] = [
  {
    id: "5-1-introduction",
    title: "5.1 Introduction",
    content:
      "A memory consists of a large array of words or bytes, each with its own address. The CPU fetches data and instructions from memory according to the program counter, possibly storing new data values as the program executes.",
  },
  {
    id: "5-2-address-binding",
    title: "5.2 Address Binding",
    content: `Binding is the mapping of addresses from one space to another. It can occur at three points:

- Compile time — the absolute address is known in advance; the program must be recompiled if its memory location changes.
- Load time — the compiler generates relocatable code; the final address is determined when the program is loaded into memory.
- Execution time — binding is delayed until runtime; requires hardware support such as base and limit registers.`,
  },
  {
    id: "5-3-logical-vs-physical-addresses",
    title: "5.3 Logical vs Physical Addresses",
    content: `A logical address (virtual address) is generated by the CPU and is what the process sees. A physical address is the actual location in RAM, seen only by the memory unit.

The Memory-Management Unit (MMU) is hardware that translates logical addresses to physical addresses by adding a relocation register value to every address a process generates.

Formula: Physical Address = Logical Address + Base Register`,
  },
  {
    id: "5-4-loading-and-linking",
    title: "5.4 Loading & Linking",
    content: `Static Linking — libraries are bundled into the executable at compile time. Every program carries its own copy, wasting disk space and memory.

Dynamic Linking — linking is deferred until execution. A stub locates the routine at runtime and replaces itself with the real address. All processes share one copy of the library. Requires OS support.

Dynamic Loading — a routine is loaded into memory only when it is called. Unused routines are never loaded, saving memory. No OS support is needed.`,
  },
  {
    id: "5-5-swapping",
    title: "5.5 Swapping",
    content: `A process is temporarily moved out of memory to a backing store (a fast disk), then brought back later to continue execution. Swap time depends on process size, transfer rate, and latency.

Sample Calculation — 20,000-word job, 250,000 words/sec transfer rate, 8 ms latency:
- Transfer time = 20,000 ÷ 250,000 = 80 ms
- One-way swap = 80 + 8 = 88 ms
- Round-trip (swap in + swap out) = 88 × 2 = 176 ms`,
  },
  {
    id: "5-6-memory-allocation-and-fragmentation",
    title: "5.6 Memory Allocation & Fragmentation",
    content: `Fragmentation Types:
- Internal fragmentation — a process is given more memory than it needs; the leftover space inside the partition is wasted.
- External fragmentation — total free memory is enough but not contiguous, so no single hole fits the process.

Allocation Policies:
- First Fit — uses the first hole large enough; fast but fragments the start of memory over time.
- Best Fit — uses the smallest hole that fits; minimizes leftover but tends to create many tiny unusable holes.
- Worst Fit — uses the largest hole; the bigger remainder is more likely to be reusable.`,
  },
  {
    id: "5-7-paging",
    title: "5.7 Paging",
    content: `Logical memory is split into fixed-size pages; physical memory is split into same-size frames. Pages load into any free frame, eliminating external fragmentation. Internal fragmentation is still possible on the last page of a process.

A logical address has two parts:
- Page number (p) — used as an index into the page table to find the frame number (f).
- Offset (d) — the position within the page.

The page table maps page numbers to frame numbers. Paging is the most widely used memory management scheme in modern operating systems.`,
  },
];

export default function Module5() {
  return null;
}